### ISSUE TITLE
Requests-Ratelimiter - documented example fails

### ISSUE THREAD

**Issue by ValueRaider** [requests-cache/requests-cache#773]
I followed the rate-limiter example here, but it prints exception below: https://requests-cache.readthedocs.io/en/stable/user_guide/compatibility.html#requests-ratelimiter

```
"requests_cache/session.py", line 74, in __init__
    super().__init__(**session_kwargs)  # type: ignore
"requests_ratelimiter/requests_ratelimiter.py", line 61, in __init__
    self.limiter = limiter or Limiter(
"pyrate_limiter/limiter.py", line 34, in __init__
    self._validate_rate_list(rates)
"pyrate_limiter/limiter.py", line 48, in _validate_rate_list
    raise InvalidParams("Rate(s) must be provided")
"pyrate_limiter.exceptions.InvalidParams: Parameters missing or invalid:Rate(s) must be provided
```

I made some progress with a small edit to `session.py`:
```
super().__init__(**get_valid_kwargs(super().__init__, kwargs, extras=["rates"]))  # type: ignore  # <- add extras
```

Now it is passing the `RequestRate` object down to `requests_ratelimiter`, but that module contains a similar problem. I hacked `requests_ratelimiter.py` to pass the object down to `pyrate_limiter`. Now the exception is solved, BUT the first get request freezes (doesn't complete).

So I suspect a more thoughtful fix is needed for total success.

**Comment by JWCook** [comment]
Ah, sorry about that, that example was for a very early version of requests-ratelimiter, and I hadn't updated it. I just fixed the example in the docs for the next release.

The short version is that I replaced the `rates` argument with arguments for the most common time intervals (`per_second`, `per_minute`, etc.), for example:
```python
from requests import Session
from requests_cache import CacheMixin, RedisCache
from requests_ratelimiter import LimiterMixin, RedisBucket


class CachedLimiterSession(CacheMixin, LimiterMixin, Session):
    """Session class with caching and rate-limiting behavior. Accepts arguments for both
    LimiterSession and CachedSession.
    """


# Optionally use Redis as both the bucket backend and the cache backend
session = CachedLimiterSession(
    per_second=5,
    bucket_class=RedisBucket,
    backend=RedisCache(),
)
```

For more complicated rate limits, you can use a `pyrate_limiter.Limiter` object, which takes a list of `Rate` objects.

There are more examples here: https://requests-ratelimiter.readthedocs.io/en/stable/index.html

**Comment by ValueRaider** [comment]
If I use `RedisBucket` the first get still freezes. Using another bucket e.g. `MemoryQueueBucket`, or not setting at all, and rate-limiting works.

**Comment by JWCook** [comment]
Do you have a Redis instance running locally? By default it will try to connect to `localhost:6379`. I just put Redis in the example to show that both libraries happen to support it as a backend. If you don't need that, then you can stick with the defaults.

If you do want to use Redis, I'll need a bit more info to help debug that. First turn on debug logging, and narrow down whether there might be a problem in requests-cache, requests-ratelimiter/pyrate-limiter, or your Redis instance. Relevant docs:
* https://requests-cache.readthedocs.io/en/stable/user_guide/backends.html
* https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.backends.redis.html
* https://pyratelimiter.readthedocs.io/en/stable/#backends

**Comment by ValueRaider** [comment]
Ah, I assumed it was in example because it would always work. I normally use SQL backend.

**Comment by JWCook** [comment]
Good point, I may remove Redis from the example and just link to the docs for using other backends.

Let me know if you run into any more issues with that.
